In [53]:
!pip install numpy
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns 
from sklearn.model_selection import train_test_split as tts
from sklearn.preprocessing import LabelEncoder

In [54]:
d=pd.read_csv(r"E:\ml datasets\diabetes.csv")
d.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [55]:
print(d.isnull().sum())
d.describe()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64


Pregnancies     Glucose  BloodPressure  SkinThickness     Insulin  \
count   768.000000  768.000000     768.000000     768.000000  768.000000   
mean      3.845052  120.894531      69.105469      20.536458   79.799479   
std       3.369578   31.972618      19.355807      15.952218  115.244002   
min       0.000000    0.000000       0.000000       0.000000    0.000000   
25%       1.000000   99.000000      62.000000       0.000000    0.000000   
50%       3.000000  117.000000      72.000000      23.000000   30.500000   
75%       6.000000  140.250000      80.000000      32.000000  127.250000   
max      17.000000  199.000000     122.000000      99.000000  846.000000   

              BMI  DiabetesPedigreeFunction         Age     Outcome  
count  768.000000                768.000000  768.000000  768.000000  
mean    31.992578                  0.471876   33.240885    0.348958  
std      7.884160                  0.331329   11.760232    0.476951  
min      0.000000                  0.078000   21.000000    0.000000  
25%     27.300000                  0.243750   24.000000    0.000000  
50%     32.000000                  0.372500   29.000000    0.000000  
75%     36.600000                  0.626250   41.000000    1.000000  
max     67.100000                  2.420000   81.000000    1.000000

In [56]:
d.Outcome.value_counts()

Outcome
0    500
1    268
Name: count, dtype: int64

In [57]:
#check for imbalence
268/500

0.536

In [58]:
x=d.drop('Outcome',axis='columns')
y=d.Outcome

In [59]:
# do scaling
from sklearn.preprocessing import StandardScaler
s=StandardScaler()
x_s=s.fit_transform(x)
x_s

array([[ 0.63994726,  0.84832379,  0.14964075, ...,  0.20401277,
         0.46849198,  1.4259954 ],
       [-0.84488505, -1.12339636, -0.16054575, ..., -0.68442195,
        -0.36506078, -0.19067191],
       [ 1.23388019,  1.94372388, -0.26394125, ..., -1.10325546,
         0.60439732, -0.10558415],
       ...,
       [ 0.3429808 ,  0.00330087,  0.14964075, ..., -0.73518964,
        -0.68519336, -0.27575966],
       [-0.84488505,  0.1597866 , -0.47073225, ..., -0.24020459,
        -0.37110101,  1.17073215],
       [-0.84488505, -0.8730192 ,  0.04624525, ..., -0.20212881,
        -0.47378505, -0.87137393]])

In [65]:
x_train, x_test, y_train, y_test =tts(x_s,y,test_size=0.25)
x_train=pd.DataFrame(x_train)
x_train.head()

0         1         2         3         4         5         6  \
0 -0.250952 -1.154694 -0.057150  0.593630  0.227496 -0.011750  0.359768   
1 -0.844885 -0.059293  0.873409  1.158182  1.217347  1.727044  1.015133   
2 -1.141852  1.849832 -0.160546  1.158182 -0.692891  1.270134  4.291962   
3 -0.250952  1.161295 -0.263941 -0.472747  2.667390 -0.100593 -0.534187   
4 -0.547919 -0.309671 -0.470732 -1.288212 -0.692891 -0.735190 -0.389222   

          7  
0 -0.701198  
1 -0.360847  
2 -0.701198  
3 -0.786286  
4 -0.871374

In [74]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import cross_val_score as cvs
cs=cvs(DecisionTreeClassifier(),x_s,y,cv=5)
cs

array([0.68831169, 0.67532468, 0.75324675, 0.78431373, 0.75816993])

In [75]:
cs.mean()

0.7318733554027672

In [79]:
from sklearn.ensemble import BaggingClassifier
bc=BaggingClassifier(
    base_estimator=DecisionTreeClassifier(),
    n_estimators=100,
    max_samples=0.8,
    oob_score=True,
    random_state=0
)
bc.fit(x_train,y_train)
bc.oob_score_

C:\Users\yadee\anaconda3\Lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(


0.7690972222222222

In [80]:
bc.score(x_test,y_test)

0.7708333333333334

In [84]:
model=DecisionTreeClassifier()
model.fit(x_train,y_train)
y_p=model.predict(x_test)

In [86]:
model.score(x_test,y_p)

1.0

In [87]:
model.score(x_train,y_train)

1.0

In [ ]:
bc.score()

In [5]:
df=pd.read_csv(r"E:\ml datasets\heart.csv")
df.head()

Age Sex ChestPainType  RestingBP  Cholesterol  FastingBS RestingECG  MaxHR  \
0   40   M           ATA        140          289          0     Normal    172   
1   49   F           NAP        160          180          0     Normal    156   
2   37   M           ATA        130          283          0         ST     98   
3   48   F           ASY        138          214          0     Normal    108   
4   54   M           NAP        150          195          0     Normal    122   

  ExerciseAngina  Oldpeak ST_Slope  HeartDisease  
0              N      0.0       Up             0  
1              N      1.0     Flat             1  
2              N      0.0       Up             0  
3              Y      1.5     Flat             1  
4              N      0.0       Up             0

In [88]:
df.isnull().sum()

Age               0
Sex               0
ChestPainType     0
RestingBP         0
Cholesterol       0
FastingBS         0
RestingECG        0
MaxHR             0
ExerciseAngina    0
Oldpeak           0
ST_Slope          0
HeartDisease      0
dtype: int64

In [103]:
le=LabelEncoder()
df.RestingECG=le.fit_transform(df.RestingECG)
df.ChestPainType=le.fit_transform(df.ChestPainType)
df.ExerciseAngina=le.fit_transform(df.ExerciseAngina)
df.ST_Slope=le.fit_transform(df.ST_Slope)
df.Sex=le.fit_transform(df.Sex)
df.head()

Age  Sex  ChestPainType  RestingBP  Cholesterol  FastingBS  RestingECG  \
0   40    1              1        140          289          0           1   
1   49    0              2        160          180          0           1   
2   37    1              1        130          283          0           2   
3   48    0              0        138          214          0           1   
4   54    1              2        150          195          0           1   

   MaxHR  ExerciseAngina  Oldpeak  ST_Slope  HeartDisease  
0    172               0      0.0         2             0  
1    156               0      1.0         1             1  
2     98               0      0.0         2             0  
3    108               1      1.5         1             1  
4    122               0      0.0         2             0

In [104]:
x=df.drop('HeartDisease',axis='columns')
y=df.HeartDisease
x_sc=s.fit_transform(x)

In [106]:
X_t, X_te, y_t, y_te=tts(x_sc,y,test_size=0.25)

In [109]:
bcc=BaggingClassifier(
    base_estimator=DecisionTreeClassifier(),
    n_estimators=100,
    max_samples=0.8,
    oob_score=True,
    random_state=0
)
bcc.fit(X_t,y_t)
bcc.oob_score_

C:\Users\yadee\anaconda3\Lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(


0.8604651162790697

In [112]:
mod=DecisionTreeClassifier()
mod.fit(X_t,y_t)
y=mod.predict(X_te)

array([0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0,
       0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0,
       1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1,
       1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1,
       0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1,
       0, 1, 0, 1, 0, 0, 0, 1, 0, 1], dtype=int64)

In [114]:
mod.score(X_te,y_te)

0.7782608695652173