In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split as tts
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier as rfc
from sklearn.metrics import confusion_matrix as cm
from sklearn.datasets import load_digits
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression as l

In [3]:
df=load_digits()

In [4]:
x_train, x_test, y_train, y_test=tts(df.data,df.target,test_size=0.3)

In [5]:
lr=l(max_iter=1000)
lr.fit(x_train,y_train)
lr.score(x_test,y_test)

C:\Users\yadee\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9518518518518518

In [6]:
rf=rfc()
rf.fit(x_train,y_train)
rf.score(x_test,y_test)

0.975925925925926

In [7]:
sm=SVC()
sm.fit(x_train,y_train)
sm.score(x_test,y_test)

0.9944444444444445

In [8]:
from sklearn.model_selection import KFold
kf=KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [9]:
for train_index,test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index,test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [10]:
def get_score(model,x_train,x_test,y_train,y_test):
    model.fit(x_train,y_train)
    return model.score(x_test,y_test)

In [11]:
get_score(rfc(),x_train,x_test,y_train,y_test)

0.9851851851851852

In [17]:
from sklearn.model_selection import StratifiedKFold
skf=StratifiedKFold(n_splits=3)
skf

StratifiedKFold(n_splits=3, random_state=None, shuffle=False)

In [19]:
# the above code are exaple for how they 
#work now we will use the reall code that need to be used in models

In [22]:
from sklearn.model_selection import cross_val_score as cvs

In [30]:
cvs(l(),x_train,y_train,cv=kf)

C:\Users\yadee\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\yadee\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_

array([0.95704057, 0.95942721, 0.95465394])

In [32]:
cvs(SVC(),x_train,y_train,cv=kf)

array([0.98090692, 0.97374702, 0.98090692])

In [33]:
cvs(rfc(),x_train,y_train,cv=kf)

array([0.96181384, 0.96181384, 0.94272076])