In [154]:
from sklearn import linear_model as lm
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import f1_score
import math 
import joblib as jb
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split as tts
from sklearn.naive_bayes import GaussianNB
from sklearn.naive_bayes import MultinomialNB

In [155]:
df=pd.read_csv(r"E:\ml datasets\titanic.csv")
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [156]:
df=df.drop(['PassengerId','Name','Cabin','SibSp','Parch','Ticket','Embarked'],axis='columns')
df.head()

Survived  Pclass     Sex   Age     Fare
0         0       3    male  22.0   7.2500
1         1       1  female  38.0  71.2833
2         1       3  female  26.0   7.9250
3         1       1  female  35.0  53.1000
4         0       3    male  35.0   8.0500

In [157]:
le=LabelEncoder()
df['Sex']=le.fit_transform(df.Sex)
df.head()

Survived  Pclass  Sex   Age     Fare
0         0       3    1  22.0   7.2500
1         1       1    0  38.0  71.2833
2         1       3    0  26.0   7.9250
3         1       1    0  35.0  53.1000
4         0       3    1  35.0   8.0500

In [158]:
df.Age=df['Age'].fillna(df.Age.mean())
df.isnull().any()

Survived    False
Pclass      False
Sex         False
Age         False
Fare        False
dtype: bool

In [159]:
x_train, x_test, y_train, y_test =tts(df.drop('Survived',axis='columns'),df.Survived)

In [160]:
model=GaussianNB()
model.fit(x_train,y_train)
y_p=model.predict(x_test[:10])

In [161]:
print(model.score(x_test[:10],y_p))
model.score(x_train,y_train)

1.0


0.7724550898203593

In [162]:
model.predict_proba(x_test[:10])

array([[0.4554099 , 0.5445901 ],
       [0.96524436, 0.03475564],
       [0.96423713, 0.03576287],
       [0.25538179, 0.74461821],
       [0.9335828 , 0.0664172 ],
       [0.75423241, 0.24576759],
       [0.92650686, 0.07349314],
       [0.45552118, 0.54447882],
       [0.96497944, 0.03502056],
       [0.96528677, 0.03471323]])

In [163]:
# E-Mail scam detector

In [164]:
d=pd.read_csv(r"E:\ml datasets\spam.csv")
d.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [165]:
d.groupby('Category').describe()

Message                                                            \
           count unique                                                top   
Category                                                                     
ham         4825   4516                             Sorry, I'll call later   
spam         747    641  Please call our customer service representativ...   

               
         freq  
Category       
ham        30  
spam        4

In [166]:
d['spam']=d['Category'].apply(lambda x: 1 if x=='spam' else 0)
d.head()

Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [167]:
x_tra,x_tes,y_tra,y_tes =tts(d.Message,d.spam,test_size=0.2)

In [168]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer()
x_tra_count=cv.fit_transform(x_tra.values)
x_tra_count.toarray()[:3]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [169]:
mod=MultinomialNB()
mod.fit(x_tra_count,y_tra)

MultinomialNB()

In [170]:
email=[
    'hey mohan we plan to give you free laptop for your birthday',
    'upto 20% offer in parking service for first 100 people'
]
email_count=cv.transform(email)
mod.predict(email_count)

array([0, 1], dtype=int64)

In [171]:
x_tes_count=cv.transform(x_tes)
mod.score(x_tes_count,y_tes)

0.9865470852017937

In [172]:
# using pipeline

In [173]:
from sklearn.pipeline import Pipeline
clf= Pipeline([
    ('vectorizer', CountVectorizer()),
    ('nb',MultinomialNB())
])

In [174]:
clf.fit(x_tra,y_tra)
clf.predict(email)

array([0, 1], dtype=int64)

In [175]:
# exercise

In [202]:
from sklearn.datasets import load_wine

In [203]:
f=load_wine()

In [204]:
dir(f)

['DESCR', 'data', 'feature_names', 'frame', 'target', 'target_names']

In [205]:
fd=pd.DataFrame(f.data,columns=f.feature_names)
fd.head()

alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
0    14.23        1.71  2.43               15.6      127.0           2.80   
1    13.20        1.78  2.14               11.2      100.0           2.65   
2    13.16        2.36  2.67               18.6      101.0           2.80   
3    14.37        1.95  2.50               16.8      113.0           3.85   
4    13.24        2.59  2.87               21.0      118.0           2.80   

   flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
0        3.06                  0.28             2.29             5.64  1.04   
1        2.76                  0.26             1.28             4.38  1.05   
2        3.24                  0.30             2.81             5.68  1.03   
3        3.49                  0.24             2.18             7.80  0.86   
4        2.69                  0.39             1.82             4.32  1.04   

   od280/od315_of_diluted_wines  proline  
0                          3.92   1065.0  
1                          3.40   1050.0  
2                          3.17   1185.0  
3                          3.45   1480.0  
4                          2.93    735.0

In [206]:
x_t,x_te,y_t,y_te =tts(f.data,f.target,test_size=0.2)

In [210]:
mo=GaussianNB()
mo.fit(x_t,y_t)
mo.predict(x_te)

array([1, 0, 0, 0, 2, 0, 1, 1, 2, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 2, 2,
       1, 0, 1, 2, 1, 1, 0, 1, 0, 1, 1, 0, 2, 1])

In [214]:
mo.score(x_te,y_te)

1.0

In [215]:
mn=MultinomialNB()
mn.fit(x_t,y_t)
mn.score(x_te,y_te)

0.8333333333333334